// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package rpc

// LoginStartRequest represents a login attempt starting with a username.
type LoginStartRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

// LoginStartResponse carries the options for the login process.
type LoginStartResponse struct {
	OptionsJson string `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
}

// LoginEndRequest finalizes the login attempt with the credential bytes.
type LoginEndRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Credential []byte `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
}

// LoginPasswordRequest is for username/password login.
type LoginPasswordRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}
